<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
  href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<link href="styles/style2.css" rel="stylesheet">
    <title>Document</title>
</head>

<body>
    <section id="contact">
        <div class="footer">
            <div class="main_footer">
                <div class="col">
                    <h4 class="footerh4">Menu Links</h4>
                    <ul class="colul">
                        <li class="colli"><a class="cola" href="index.php">Home</a></li>
                        <li class="colli"><a class="cola" href="product.php">Product</a></li>
                        <li class="colli"><a class="cola" href="feature.php">Feature</a></li>
                        <li class="colli"><a class="cola" href="https://docs.google.com/presentation/d/1Xc72srxVfJb2KKmyQMamVlhVpq7mFbDKHdMxTwWgAUc/edit?usp=sharing">Powerpoint</a></li>
                    </ul>
                </div>

                <div class="col">
                    <h4 class="footerh4">Our Product</h4>
                    <ul class="colul">
                        <li class="colli"><a class="cola" href="https://www.youtube.com/watch?v=od9dfaLA91w">Video</a></li>
                        <li class="colli"><a class="cola" href="https://github.com/giang6996/Ackathon">Download code here</a></li>
                    </ul>
                </div>

                <div class="col">
                    <h4 class="footerh4">Information</h4>
                    <ul class="colul">
                        <li class="colli"><a class="cola" href="#">Nguyen Hoang Nguyen</a></li>
                        <li class="colli"><a class="cola" href="#">Nguyen Canh Giang</a></li>
                        <li class="colli"><a class="cola" href="#">Nguyen Huu Duc Anh</a></li>
                    </ul>
                </div>

                <div class="col">
                    <h4 class="footerh4">Information</h4>
                    <div class="socials">
                        <a class="colasocial" href=""><i class='bx bxl-facebook'></i></a>
                        <a class="colasocial" href=""><i class='bx bxl-instagram' ></i></a>
                        <a class="colasocial" href=""><i class='bx bxl-twitter' ></i></a>
                        <a class="colasocial" href=""><i class='bx bxl-youtube' ></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>
